// *USER RELATED 
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_LOADING = 'SET_LOADING';
export const SET_PROFILE_PHOTO = 'SET_PROFILE_PHOTO';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';


// *DATA RELATED
export const SET_CHATS = 'SET_CHATS';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';
export const SET_USER_ONLINE = 'SET_USER_ONLINE';
export const READ_MESSAGES = 'READ_MESSAGES';
export const SET_LOCAL_FILE_PATH = 'SET_LOCAL_FILE_PATH';
export const SET_CLOUD = 'SET_CLOUD';
export const DELETE_CHAT = 'DELETE_CHAT';

